java-spring-fullstack:
  display-name: java-spring-fullstack

server:
  port: ${PORT:8080}
  servlet:
    application-display-name: ${spring.application.name}

spring:
  profiles:
    active: ${PROFILE:default}
  application:
    name: ${java-spring-fullstack.display-name}
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_USER:dev}
      password: ${MONGO_PASSORD:dev}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
      database: ${MONGO_DATABASE:dev}
  messages:
    basename: messages
    encoding: UTF-8

info:
  component: ${ml-simian.display-name}
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@


# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"